### ISSUE TITLE
`--no-total` and `--legend-cutoff` options like `sumo`

### ISSUE THREAD

**Issue by kavanase** [SMTG-Bham/galore#42]
I think CLI options `--no-total` (to hide the solid black line of the total XPS spectrum) and `--legend-cutoff` options as available with `sumo-dosplot` would be nice additions to the functionality of Galore.

They would be useful options to improve the clarity of output XPS plots, as often the orbital character of the XPS peaks are hidden by the solid black line (if only a single orbital contribution dominates at a given energy range, as is typical) and also the legend often includes many orbital contributions that have negligible contributions to the XPS spectrum. 

For example:
<img width="834" alt="image" src="https://user-images.githubusercontent.com/51478689/135480941-30fd7873-fa0b-4efd-a201-23ead62fc5bd.png">

**Comment by ajjackson** [comment]
Yup, both of those make sense. The slightly tricky business with legend cutoffs is that they depend on the plotting region rather than the full spectrum. If anything that is easier in galore, as we resample first.

**Comment by kavanase** [comment]
Closing because this was added in #44
