### ISSUE TITLE
`--fill-between` option

### ISSUE THREAD

**Issue by kavanase** [SMTG-Bham/galore#43]
Similar to issue #42, I think a `--fill-between` CLI option would be a nice addition to the functionality of Galore, where this gives an output XPS plot with a semi-transparent fill for each orbital contribution (as with `sumo-dosplot`) which would aid the clarity of the output plots.

I'll try implement this in my local version of `galore` and make a PR soon.

**Comment by kavanase** [comment]
Like this (plus with a `legend-cutoff` here as well):
<img width="864" alt="image" src="https://user-images.githubusercontent.com/51478689/135492864-9fda8730-125c-43c4-bd2b-aff7ca4baac8.png">

c.f. original:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/51478689/135492900-65add87c-2541-4f76-856c-51f5200ab287.png">

**Comment by ajjackson** [comment]
That is a bit nicer to interpret! Why `fill-between` though? (Apart from the Matplotlib implementation detail...) If we are filling between a line and zero, I think the intuitive option would just be `--fill`?

**Comment by kavanase** [comment]
Yep makes sense! Was just going with the matplotlib syntax but that would be more intuitive. I think it might make sense to fill by default and instead have a `--no-fill` option, what do you think?
